---
- name: Setup metricbeat
  hosts: webservers
  remote_user: azadmin
  become: true
  tasks:
  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install metricbeat
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Copy configuration file
    copy:
      src: /etc/metricbeat/metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable metricbeat modules
    command: metricbeat modules enable docker

  - name: Setup metricbeat
    command: metricbeat setup

  - name: Start metricbeat
    command: service metricbeat start

  - name: Ensure metricbeat running
    systemd:
      state: started
      name: metricbeat
